/**
 * Built-in regional information, re-generated by `npm run build`.
 *
 * @generated 2025-03-04T22:05:45.653Z
 */
export declare class BuiltIns {
    /**
     * Registers all the built in regional data in the RegionInfo database.
     */
    static register(): void;
    private constructor();
}
